# Site settings
title: PRopp42
email: focusSwordsman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of rambling by Patrick Ropp.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: FocusSwordsMan
github_username:  PRopp42

# Build settings
markdown: kramdown
